package ui;

import Model.PersonHistory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rutuj
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonHistory personHistory;
    public MainJFrame(PersonHistory personHistory) {
        initComponents();
        this.personHistory = personHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnSystem = new javax.swing.JButton();
        BtnHospital = new javax.swing.JButton();
        BtnCommunity = new javax.swing.JButton();
        BtnDoctor = new javax.swing.JButton();
        BtnPatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSystem.setText("System Admin");
        BtnSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSystemActionPerformed(evt);
            }
        });

        BtnHospital.setText("Hospital");
        BtnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHospitalActionPerformed(evt);
            }
        });

        BtnCommunity.setText("Community");
        BtnCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCommunityActionPerformed(evt);
            }
        });

        BtnDoctor.setText("Doctor");
        BtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoctorActionPerformed(evt);
            }
        });

        BtnPatient.setText("Patient");
        BtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(BtnHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(678, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(BtnSystem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnHospital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCommunity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPatient)
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHospitalActionPerformed
        // TODO add your handling code here:
        HospitalLoginForm HF = new HospitalLoginForm();
        HF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnHospitalActionPerformed

    private void BtnCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCommunityActionPerformed
        // TODO add your handling code here:
        CommunityLoginForm CF = new CommunityLoginForm();
        CF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCommunityActionPerformed

    private void BtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPatientActionPerformed
        // TODO add your handling code here:
        PatientLoginForm PF = new PatientLoginForm();
        PF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPatientActionPerformed

    private void BtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoctorActionPerformed
        // TODO add your handling code here:
        DoctorLoginForm DF = new DoctorLoginForm(personHistory);
        DF.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnDoctorActionPerformed

    private void BtnSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSystemActionPerformed
        // TODO add your handling code here:
        SystemLoginForm SF = new SystemLoginForm();
        SF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSystemActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCommunity;
    private javax.swing.JButton BtnDoctor;
    private javax.swing.JButton BtnHospital;
    private javax.swing.JButton BtnPatient;
    private javax.swing.JButton BtnSystem;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
