/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class SystemAdminLoginForm extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminLoginForm
     */
    public SystemAdminLoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnslogin = new javax.swing.JButton();
        lblsusername = new javax.swing.JLabel();
        lblspassword = new javax.swing.JLabel();
        txtsusername = new javax.swing.JTextField();
        txtspassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        btnslogin.setText("Login");
        btnslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsloginActionPerformed(evt);
            }
        });

        lblsusername.setText("Username:");

        lblspassword.setText("Password:");

        jLabel1.setText("System Admin Login Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnslogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblspassword)
                                .addGap(18, 18, 18)
                                .addComponent(txtspassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblsusername)
                                .addGap(18, 18, 18)
                                .addComponent(txtsusername, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsusername)
                    .addComponent(txtsusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblspassword)
                    .addComponent(txtspassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnslogin)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsloginActionPerformed
        // TODO add your handling code here:
        if (lblsusername.getText().equals("systemadmin") && lblspassword.getText().equals("123456")){

        
         SystemAdminLoginForm SALF = new SystemAdminLoginForm();
         SALF.setVisible(true);
         this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter correct username and password", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnsloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnslogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblspassword;
    private javax.swing.JLabel lblsusername;
    private javax.swing.JTextField txtspassword;
    private javax.swing.JTextField txtsusername;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
